site_name: Kay McNulty - QSW
site_description: Documentação oficial do grupo Kay McNulty
site_url: https://FCTE-Qualidade-de-Software-1.github.io/2025-1-T01-KAY-MCNULTY
site_author: Grupo Kay McNulty
repo_name: Kay McNulty - QSW
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T01-KAY-MCNULTY
edit_uri: edit/docs/docs/

theme:
  name: material
  language: pt-BR
#  logo: assets/logo/logo.png
#  favicon: assets/logo/logo.png
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.annotate
    - navigation.top
  palette:
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid      # habilita ```mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.tabbed
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github

nav:
  - Início: index.md